openapi: 3.0.3

info:
  title: ONEx Fabric API
  description: |-
    The Open Network Experiments Fabric API and Data Models
  version: 0.0.1
  contact:
    x-info: |-
      Any feedback such as bugs/enhancements/questions regarding the 
      Fabric API and Data models is welcomed by using the contact url.
    url: https://github.com/open-network-experiments/issues
  license:
    name: MIT

servers:
  - url: https://{hostname}:{port}/{basePath}
    variables:
      hostname:
        default: 0.0.0.0
      port:
        default: '443'
      basePath:
        default: /onex/api/v1/fabric

paths:
  /config:
    put:
      tags: ["Configuration"]
      operationId: set_config
      description: >-
        Sets the ONEx fabric configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./config.yaml#/components/schemas/Config"
      responses:
        x-include:
          - "../common/common.yaml#/components/responses/Success"
          - "../common/common.yaml#/components/responses/Error400"
          - "../common/common.yaml#/components/responses/Error500"
    get:
      tags: ["Configuration"]
      operationId: get_config
      description: >-
        Gets the ONEx fabric configuration.
      responses:
        '200':
          description: Current ONEx fabric configuration.
          content:
            application/json:
              schema:
                $ref: "./config.yaml#/components/schemas/Config"
        x-include:
          - "../common/common.yaml#/components/responses/Error400"
          - "../common/common.yaml#/components/responses/Error500"

  /state:
    put:
      tags: ["State"]
      operationId: set_state
      description: >-
        Updates the state of ONEx configured experiment(s).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../model/state/state.yaml#/components/schemas/State"
      responses:
        x-include:
          - "../common/common.yaml#/components/responses/Success"
          - "../common/common.yaml#/components/responses/Error400"
          - "../common/common.yaml#/components/responses/Error500"
    get:
      tags: ["State"]
      operationId: get_state
      description: >-
        Gets the state of ONEx configured experiments.
      responses:
        '200':
          description: Current ONEx experiment(s) state.
          content:
            application/json:
              schema:
                $ref: "../model/state/state.yaml#/components/schemas/State"
        x-include:
          - "../common/common.yaml#/components/responses/Error400"
          - "../common/common.yaml#/components/responses/Error500"

  
