openapi: 3.0.3

info:
  title: ONEx Fabric API
  description: |-
    The Open Network Experiments Fabric API and Data Models
  version: 0.0.1
  contact:
    x-info: |-
      Any feedback such as bugs/enhancements/questions regarding the 
      Fabric API and Data models is welcomed by using the contact url.
    url: https://github.com/open-network-experiments/issues
  license:
    name: MIT

servers:
  - url: /

paths:
  /config:
    post:
      tags: ["Configuration"]
      operationId: set_config
      description: >-
        Sets the fabric configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./config.yaml#/components/schemas/Config"
      responses:
        x-include:
          - "../common/common.yaml#/components/responses/Success"
          - "../common/common.yaml#/components/responses/Error400"
          - "../common/common.yaml#/components/responses/Error500"
    get:
      tags: ["Configuration"]
      operationId: get_config
      description: >-
        Gets the fabric configuration.
      responses:
        '200':
          description: The current configured fabric configuration.
          content:
            application/json:
              schema:
                $ref: "./config.yaml#/components/schemas/Config"
        x-include:
          - "../common/common.yaml#/components/responses/Error400"
          - "../common/common.yaml#/components/responses/Error500"