components:
  schemas:
    Config:
      description: |-
        The resources that define a dataflow configuration. 
      type: object
      properties:
        hosts:
          type: array
          items:
            $ref: "../model/host/host.yaml#/components/schemas/Host"
        dataflow:
            $ref: "../model/dataflow/dataflow.yaml#/components/schemas/Dataflow"
