components:
  schemas:
    Config:
      description: |-
        The resources that define a fabric configuration.
      type: object
      properties:
        hosts:
          type: array
          items:
            $ref: "./host/host.yaml#/components/schemas/Host"
        fabric:
            $ref: "./fabric/fabric.yaml#/components/schemas/Fabric"
        dataflow:
            $ref: "./dataflow/dataflow.yaml#/components/schemas/Dataflow"

