components:
  responses: {}
  schemas:
    Error.Details:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    Warning.Details:
      type: object
      properties:
        warnings:
          type: array
          items:
            type: string
    Config:
      description: |-
        The resources that define a fabric configuration.
      type: object
      properties:
        hosts:
          type: array
          items:
            $ref: '#/components/schemas/Host'
        servers:
          type: array
          items:
            $ref: '#/components/schemas/Server'
        fabric:
          $ref: '#/components/schemas/Fabric'
        dataflow:
          $ref: '#/components/schemas/Dataflow'
    Host:
      required:
      - address
      - name
      properties:
        front_panel_port:
          description: |-
            The number of the port on the front panel
          type: integer
        name:
          description: |-
            The name, uniquely identifying the host
          type: string
        address:
          description: |-
            The test address of the host
          type: string
        prefix:
          description: |-
            The prefix of the host
          type: integer
          default: 24
    Server:
      properties:
        mac_address:
          description: |-
            The mac address
          type: string
          format: mac
        name:
          description: |-
            Unique identifier for an object
          type: string
          format: global-unique
      type: object
    Fabric:
      type: object
      properties:
        choice:
          type: string
          enum:
          - spine_pod_rack
        spine_pod_rack:
          $ref: '#/components/schemas/Fabric.SpinePodRack'
        qos_profiles:
          description: |-
            A list of Quality of Service (QoS) profiles
          type: array
          items:
            $ref: '#/components/schemas/Fabric.QosProfile'
    Fabric.SpinePodRack:
      description: |-
        An emulation of a spine/pod/rack topology
      type: object
      properties:
        spines:
          description: |-
            The spines in the topology.
          type: array
          items:
            $ref: '#/components/schemas/Fabric.Spine'
        pods:
          description: |-
            The pods in the topology.
          type: array
          items:
            $ref: '#/components/schemas/Fabric.Pod'
        links:
          type: array
          items:
            $ref: '#/components/schemas/Fabric.Link'
        parallel_fabric_count:
          type: integer
          default: 1
        pod_profiles:
          description: |-
            A list of pod profiles
          type: array
          items:
            $ref: '#/components/schemas/Fabric.PodProfile'
        rack_profiles:
          description: |-
            A list of rack profiles
          type: array
          items:
            $ref: '#/components/schemas/Fabric.RackProfile'
    Fabric.Spine:
      type: object
      properties:
        count:
          description: |-
            The number of spines to be created with each spine sharing the same
            downlink_ecmp_mode and qos_profile_name properties.
          type: integer
          default: 1
        downlink_ecmp_mode:
          description: "The algorithm for packet distribution over ECMP links.\n-\
            \ random_spray randomly puts each packet on an ECMP member links \n- hash_3_tuple\
            \ is a 3 tuple hash of ipv4 src, dst, protocol\n- hash_5_tuple is static_hash_ipv4_l4\
            \ but a different resulting RTAG7 hash mode"
          type: string
          enum:
          - random_spray
          - hash_3_tuple
          - hash_5_tuple
        qos_profile_name:
          description: |
            The name of a qos profile shared by the spines.

            x-constraint:
            - #/components/schemas/QosProfile/properties/name
          type: string
          x-constraint:
          - '#/components/schemas/QosProfile/properties/name'
    Fabric.Pod:
      type: object
      properties:
        count:
          description: |-
            The number of pods that will share the same profile
          type: integer
          default: 1
        pod_profile_name:
          description: |-
            The pod profile associated with this pod.
          type: array
          items:
            type: string
            x-constraint:
            - '#/components/schemas/PodProfile/properties/name'
            description: |
              TBD

              x-constraint:
              - #/components/schemas/PodProfile/properties/name
    Fabric.PodProfile:
      type: object
      properties:
        name:
          type: string
        pod_switch:
          $ref: '#/components/schemas/Fabric.PodSwitch'
        rack:
          $ref: '#/components/schemas/Fabric.Rack'
        annotations:
          type: array
          items:
            $ref: '#/components/schemas/Annotations'
    Fabric.PodSwitch:
      type: object
      properties:
        count:
          type: integer
          default: 1
        pod_to_spine_oversubscription:
          description: |-
            oversubscription ratio of the pod switches
          type: string
        uplink_ecmp_mode:
          description: "The algorithm for packet distribution over ECMP links.\n-\
            \ random_spray randomly puts each packet on an ECMP member links \n- hash_3_tuple\
            \ is a 3 tuple hash of ipv4 src, dst, protocol\n- hash_5_tuple is static_hash_ipv4_l4\
            \ but a different resulting RTAG7 hash mode"
          type: string
          enum:
          - random_spray
          - hash_3_tuple
          - hash_5_tuple
        downlink_ecmp_mode:
          description: "The algorithm for packet distribution over ECMP links.\n-\
            \ random_spray randomly puts each packet on an ECMP member links \n- hash_3_tuple\
            \ is a 3 tuple hash of ipv4 src, dst, protocol\n- hash_5_tuple is static_hash_ipv4_l4\
            \ but a different resulting RTAG7 hash mode"
          type: string
          enum:
          - random_spray
          - hash_3_tuple
          - hash_5_tuple
        qos_profile_name:
          description: |
            The name of a qos profile associated with this pod switch.

            x-constraint:
            - #/components/schemas/QosProfile/properties/name
          type: string
          x-constraint:
          - '#/components/schemas/QosProfile/properties/name'
    Fabric.Rack:
      type: object
      properties:
        rack_profile_names:
          description: |-
            The names of rack profiles associated with this rack.
          type: array
          items:
            type: string
            x-constraint:
            - '#/components/schemas/RackProfile/properties/name'
            description: |
              TBD

              x-constraint:
              - #/components/schemas/RackProfile/properties/name
    Fabric.RackProfile:
      type: object
      properties:
        name:
          type: string
        tor_uplink_ecmp_mode:
          description: "The algorithm for packet distribution over ECMP links.\n-\
            \ random_spray randomly puts each packet on an ECMP member links \n- hash_3_tuple\
            \ is a 3 tuple hash of ipv4 src, dst, protocol\n- hash_5_tuple is static_hash_ipv4_l4\
            \ but a different resulting RTAG7 hash mode"
          type: string
          enum:
          - random_spray
          - hash_3_tuple
          - hash_5_tuple
        tor_downlink_ecmp_mode:
          description: "The algorithm for packet distribution over ECMP links.\n-\
            \ random_spray randomly puts each packet on an ECMP member links \n- hash_3_tuple\
            \ is a 3 tuple hash of ipv4 src, dst, protocol\n- hash_5_tuple is static_hash_ipv4_l4\
            \ but a different resulting RTAG7 hash mode"
          type: string
          enum:
          - random_spray
          - hash_3_tuple
          - hash_5_tuple
        tor_qos_profile_name:
          description: |
            The name of a qos profile associated with the ToR of this rack

            x-constraint:
            - #/components/schemas/QosProfile/properties/name
          type: string
          x-constraint:
          - '#/components/schemas/QosProfile/properties/name'
        tor_to_pod_oversubscription:
          description: |-
            The oversubscription ratio of the ToR switch
          type: string
    Fabric.QosProfile:
      type: object
      required:
      - name
      properties:
        name:
          type: string
        ingress_admission:
          $ref: '#/components/schemas/Fabric.QosProfile.IngressAdmission'
        scheduler:
          $ref: '#/components/schemas/Fabric.QosProfile.Scheduler'
        packet_classification:
          $ref: '#/components/schemas/Fabric.QosProfile.PacketClassification'
    Fabric.QosProfile.IngressAdmission:
      type: object
      properties:
        reserved_buffer_bytes:
          description: |-
            Buffer space (in bytes) reserved for each port that this Qos profile applies to
          type: integer
          default: 0
        shared_buffer_bytes:
          description: |-
            Amount of shared buffer space (in bytes) available
          type: integer
          default: 0
    Fabric.QosProfile.Scheduler:
      type: object
      properties:
        scheduler_mode:
          description: "The queue scheduling discipline "
          type: string
          enum:
          - strict_priority
          - weighted_round_robin
        weight_list:
          description: |-
            A list of queue weights
          type: array
          items:
            type: integer
    Fabric.QosProfile.PacketClassification:
      type: object
      properties:
        map_dscp_to_traffic_class:
          $ref: '#/components/schemas/Fabric.QosProfile.PacketClassification.Map'
        map_traffic_class_to_queue:
          $ref: '#/components/schemas/Fabric.QosProfile.PacketClassification.Map'
    Fabric.QosProfile.PacketClassification.Map:
      type: object
      additionalProperties:
        type: string
    Annotations:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    Fabric.Link:
      type: object
      description: "The ingress point of a host which is the index of a spine switch,\
        \ \na pod/rack switch."
      properties:
        host_name:
          type: string
          x-constraint:
          - '#components/schemas/Host/properties/name'
          description: |
            TBD

            x-constraint:
            - #components/schemas/Host/properties/name
        choice:
          type: string
          enum:
          - spine
          - pod
          - rack
        spine:
          description: "One based index of the spine switch based on the number of\
            \ spines \nconfigured in the spine_pod_rack topology."
          type: integer
          minimum: 1
        pod:
          $ref: '#/components/schemas/Link.PodRackLink'
        rack:
          $ref: '#/components/schemas/Link.PodRackLink'
    Link.PodRackLink:
      description: |-
        Location of the switch based on the number of pods and rack switches.
      type: object
      properties:
        pod_index:
          description: |-
            Index of the pod switch based on the number of pods and pod switches.
          type: integer
          minimum: 1
        switch_index:
          description: |-
            Index of the rack switch based on the number of pods and rack switches.
          type: integer
          minimum: 1
    Dataflow:
      type: object
      properties:
        host_names:
          type: array
          items:
            type: string
          x-constraint:
          - '#/components/schemas/Host/properties/name'
          description: |
            TBD

            x-constraint:
            - #/components/schemas/Host/properties/name
        workload:
          description: |-
            The workload items making up the dataflow
          type: array
          items:
            $ref: '#/components/schemas/Dataflow.WorkloadItem'
        flow_profiles:
          description: |-
            foo
          type: array
          items:
            $ref: '#/components/schemas/Dataflow.FlowProfile'
    Dataflow.FlowProfile:
      type: object
      required:
      - name
      - data_size
      properties:
        name:
          type: string
        data_size:
          type: integer
    Dataflow.WorkloadItem:
      type: object
      required:
      - name
      - choice
      properties:
        name:
          description: |-
            uniquely identifies the workload item
          type: string
        choice:
          description: |-
            The type of workflow item
          type: string
          enum:
          - scatter
          - loop
          - compute
          - all_reduce
        scatter:
          $ref: '#/components/schemas/Dataflow.ScatterWorkload'
        loop:
          $ref: '#/components/schemas/Dataflow.LoopWorkload'
        compute:
          $ref: '#/components/schemas/Dataflow.ComputeWorkload'
        all_reduce:
          $ref: '#/components/schemas/Dataflow.AllReduceWorkload'
    Dataflow.ScatterWorkload:
      type: object
      properties:
        sources:
          description: |-
            list of host names, indicating the originator of the data
          type: array
          items:
            type: string
        destinations:
          description: |-
            list of host names, indicating the destination of the data
          type: array
          items:
            type: string
        flow_profile_name:
          description: |-
            flow profile reference
          type: string
    Dataflow.AllReduceWorkload:
      type: object
      properties:
        nodes:
          type: array
          items:
            type: string
        flow_profile_name:
          description: |-
            flow profile reference
          type: string
        type:
          description: |-
            type of all reduce
          type: string
          enum:
          - ring
    Dataflow.ComputeWorkload:
      type: object
      properties:
        nodes:
          type: array
          items:
            type: string
        choice:
          description: |-
            type of compute
          type: string
          enum:
          - simulated
        simulated:
          $ref: '#/components/schemas/Dataflow.SimulatedComputeWorkload'
    Dataflow.SimulatedComputeWorkload:
      type: object
      properties:
        duration:
          description: |-
            duration of the simulated compute workload in seconds
          type: number
    Dataflow.LoopWorkload:
      type: object
      properties:
        iterations:
          description: |-
            number of iterations in the loop
          type: integer
        children:
          description: |-
            list of workload items that are executed in this loop
          type: array
          items:
            $ref: '#/components/schemas/Dataflow.WorkloadItem'
openapi: 3.0.3
info:
  title: ONEx Data Models
  description: |-
    The data models for the entire ONEx ecosystem
  version: 0.0.1
  contact:
    x-info: "Any feedback such as bugs/enhancements/questions regarding the \nONEx\
      \ data models is welcomed by using the contact url."
    url: https://github.com/onex/models/issues
  license:
    name: MIT
servers:
- url: /
paths:
  /config:
    post:
      tags:
      - Configuration
      operationId: set_config
      description: |-
        A placeholder API that returns nothing. It is used by the OpenAPIArt package to generate UX SDK objects.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          description: |-
            Success with possible warnings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Warning.Details'
